# Generated by Django 5.2.7 on 2025-11-03 20:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('area', models.FloatField(help_text='Total area of the farm in hectares')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('wheat', 'Wheat'), ('corn', 'Corn'), ('rice', 'Rice'), ('barley', 'Barley')], max_length=10)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area', models.FloatField(help_text='Area of this field (ha)')),
                ('planted_on', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farmadmin.farm')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('water_source', models.CharField(help_text='Water source (well, canal, etc.)', max_length=100)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_points', to='farmadmin.field')),
            ],
        ),
    ]
